src/client/views/icon-view.ts
src/client/views/select-issuers.ts
src/client/views/token-list.ts
src/theme/style.css

Hey @nicktaras,
This adds: 
- Image loading shimmer effect
- loading="lazy" to images
- fallback avatar image in the case image fails to load or if the image src is undefined.

Added image loading shimmer, lazyload & fallback avatar.

---

src/client/views/select-wallet.ts
src/utils/Web3WalletProvider.ts

Hey @nicktaras this just adds a small fix to handle wallet connect errors.

Fix wallet connect user-dismiss error.

---

package-lock.json
package.json
src/client/index.ts
src/outlet/auth-handler.ts
src/tokenLookup.ts

Hey @nicktaras 
This PR adds ZK proof validation into the TN client authenticate function.

Added ticket proof validation to client.

---

package-lock.json
package.json
src/asn/SignedDevconTicket.ts
src/client/__tests__/client.spec.ts
src/core/__tests__/core.spec.ts
src/outlet/index.ts

- Update attestation library to fix Buffer conversion issue.
- Updates browser list to ensure exponent operators are not
converted to Math.pow.
- Various other fixes for individual tests.

Fix various test issues

---

src/client/index.ts
src/client/messaging.ts
src/core/index.ts
src/outlet/auth-handler.ts
src/outlet/index.ts
src/theme/style.css
src/utils/index.ts

@nicktaras , @micwallace , can you check my updates.
I had to update it to work OK with devconnect
I used those updates with UMD version.

off-chain attestation fixes

---

src/client/index.ts
src/client/messaging.ts
src/outlet/auth-handler.ts
src/outlet/index.ts

updates according to the https://github.com/AlphaWallet/attestation.id/pull/134
and handled reject on user close popup to pass event to the parent app, I missed this option for devconnect.
@micwallace , @AW-STJ

sync address with attestation.id, handled reject on user close popup

---

package.json

Updated NPM Package Version only.

updated npm pkg version

---

src/client/index.ts
src/client/interface.ts

As requested by @oleggrib in #248

Add force tab option

---

src/client/index.ts
src/client/interface.ts
src/client/ui.ts
src/client/views/select-issuers.ts
src/client/views/select-wallet.ts
src/client/views/start.ts
src/client/views/view-interface.ts
src/theme/style.css

This PR adds the following features: 
- New inline UIType option inserts TN UI in an element of the developers choosing. 
- Contract metadata is now loaded asynchronously to prevent it from blocking UI initialization. 
- UI functions are exposed through client getUI function. This allows the developer to utilize TN's UI for custom loading and error messages.

Inline UI and async contract metadata load

---

README.md
src/client/index.ts
src/utils/support/__tests__/getBrowswerData.spec.ts
src/utils/support/__tests__/isSupported.spec.ts
src/utils/support/getBrowserData.ts
src/utils/support/isSupported.ts

Fixed code, tested code for imToken, MEW, Metamask, AlphaWallet, Android Chrome, Android Firefox, Mac Desktop Browsers...

fix: 🐛 fixed code for browser support

---

src/wallet/SafeConnectProvider.ts

Hey @nicktaras 
Just some very minor changes for safe connect compatibility.

Small updates for SafeConnect compatibility

---

src/client/index.ts
src/client/interface.ts
src/utils/support/isSupported.ts

I unfortunately finished this commit before I realized that @oleggrib had fixed the same thing.
Let's benchmark both of these and let the most efficient be merged :-)

Fix config merge

---

src/client/index.ts
src/client/tokenStore.ts
src/client/ui.ts
src/client/views/start.ts

This PR delays contract data download until the user interacts with TN, by clicking the "Let's Go" button on the Start view.

Feature: delay contract meta load

---

src/client/__tests__/auth.spec.ts
src/wallet/__test__/wallet.spec.ts

TKN-248: 
- add wallet.spec.ts for Unit test coverage of wallet

Wallet test coverage

---

src/core/messaging.ts
src/outlet/auth-handler.ts
src/outlet/index.ts
src/theme/style.css
src/utils/support/__tests__/getBrowswerData.spec.ts
src/utils/support/getBrowserData.ts

when we open attestation in new tab then we have opened iframe with button(user click button to open new tab)
I have added messaging in iframe about attestation
also added child tab state detector
also we can set size of iframe , sometimes it looks better in smaller size

Oh iframe messaging

---

src/client/views/select-issuers.ts
src/outlet/index.ts

Fixed view (content was invisible)
content added in correct way (original page was broken)
disabled storage API request for browsers, which doesnt support it
updated ticket name (new tickets use _ticket_ , not _tiket_)
cc @nicktaras

fix: 🐛 fixed code to work with firefox and chrome and dont fail

---

src/client/auth/ticketZKProof.ts
src/client/index.ts
src/outlet/auth-handler.ts
src/outlet/index.ts
src/outlet/localOutlet.ts

This PR allows tokens to be loaded directly from local storage when negotiator is used on the same origin as the outlet

feature: load tokens directly for same-origin outlets

---

LICENSE

Tkn 244 add license file to the token negotiator

---

index.html
src/client/index.ts
src/utils/__tests__/util.spec.ts
src/utils/index.ts
src/utils/support/isSupported.ts

PR for general error handler in TN

feat: added error handler

---

src/client/index.ts
src/utils/index.ts

@nicktaras Here are some fixes for error handling

Fix: errorhandler action param

---

src/client/auth/util/SafeConnect.ts
src/core/messaging.ts

@nicktaras fixes TECH-222 in Jira.

Fix: message params bug

---

src/client/__tests__/client.spec.ts
src/client/index.ts
src/client/interface.ts
src/client/tokenStore.ts
src/client/ui.ts
src/client/views/select-issuers.ts
src/client/views/select-wallet.ts
src/client/views/start.ts
src/theme/common.scss
src/theme/theme_dark.scss
webpack.config.js

This feature adds token persistence via local storage. The TTL for saved tokens and contract data can be configured via the tokenPersistenceTTL config value.
It also adds skipping of the start screen if tokens are already persisted. The start screen can always be shown like before by setting the uiOptions.alwaysShowStartScreen option to false.

Feature: token persistence

---

.husky/pre-commit
src/client/index.ts
src/client/interface.ts
src/client/tokenStore.ts
src/client/views/select-issuers.ts
src/client/views/token-list.ts
src/utils/token/__tests__/onchaintoken.spec.ts
src/utils/token/fungibleTokenProvider.ts
src/utils/token/nftProvider.ts

Hey @BankiLouis 
This PR fixes various issues in the ERC-20 token implementation.
Requires: https://github.com/TokenScript/tn-token-discovery-api/pull/27
- Add contract metadata endpoints
- Prevent reload of contract data
- Fix autoload from loading already loaded tokens
- Reduce code repetition in fungibleTokenProvider.ts
- Fix UI issuerConnectMarkup for already loaded tokens
- Remove various uses of "any" type
- Prevent null icon from loading in image view
- Add token balance
The goal is to work together to get it into a stable condition for the next release. Please see the token discovery API PR first, review & approve. Then we can merge these changes which will take care of most of the change requests in your PR.

Fix: erc20 issues

---

src/client/index.ts
src/wallet/Web3WalletProvider.ts

re: chain switch regression

---

package.json
scripts/write_version_constant.js

✅ Closes: https://smarttokenlabs.atlassian.net/browse/TKS-792 https://smarttokenlabs.atlassian.net/browse/TKS-800
Hi @nicktaras . This PR will fix Windows build. Please check & merge. After merge this PR, this branch could be removed.
Thanks.

chore: 🤖 make npm scripts could also run on Windows

---

README.md
src/client/index.ts
src/client/ui.ts
src/client/views/select-issuers.ts
src/client/views/select-wallet.ts
src/client/views/start.ts
src/client/views/token-list.ts
src/client/views/view-interface.ts
src/theme/common.scss
src/wallet/Web3WalletProvider.ts

Implement the following view transitions that can be applied by passing the options.viewTransition property to the UI.updateUI function or specifying it in the viewOverrides config options:
- slide-in-left
- slide-in-right
- slide-in-top
- slide-in-bottom
Inbuilt views have been updated to use the left/right transition.

Feature: view transitions

---

src/client/views/select-wallet.ts
src/wallet/Web3WalletProvider.ts

fix: 🐛 error handle for Flow popup close

---

index.html
package-lock.json
package.json
src/client/index.ts
src/client/interface.ts
src/client/views/select-wallet.ts
src/wallet/MagicLinkProvider.ts
src/wallet/Web3WalletProvider.ts
webpack.config.js

- Add Magic.Link wallet provider.
- Add option to show experimental features & apply to WCv2 & Magic.Link.

feat: Add magic.link wallet & only show wallets for configured issuers

---

src/client/index.ts
src/client/views/select-wallet.ts
src/wallet/Web3WalletProvider.ts

Fixes:
- WC2 stuck on Reject
- WC2 receive empty address
- WC2 double login

fix: 🐛 fixed WC2 flow

---

README.md

Add one warning for the case of solana

Update readme for solana issuers

---

.github/workflows/tn-p1.yml
.github/workflows/tn-snapshot.yml

✅ Closes: https://smarttokenlabs.atlassian.net/browse/TKS-969

ci: 🎡 SNAPSHOT-staging to use attestation@SNAPSHOT-staging

---

src/client/views/select-wallet.ts
src/client/views/utils/wallet-info.ts
src/utils/support/__tests__/getBrowswerData.spec.ts
src/utils/support/getBrowserData.ts

fixes https://smarttokenlabs.atlassian.net/browse/TKS-603
also added fix when TN breaks when no solana extension added

feat: 🎸 disable torus in edge_ios, solana fix

---

CHANGELOG.md
package.json
src/core/index.ts
src/core/messaging.ts
src/outlet/localOutlet.ts
src/utils/index.ts
src/version.ts

Release Prep, update to the package.json and change log.

updated version and changelog

---

src/outlet/index.ts

Really minor change added to align the button styles to all use, cursor: pointer for the TKN UX.

added cursor style to buttons for outlet

---

src/theme/common.scss

This ticket is related to https://smarttokenlabs.atlassian.net/jira/software/c/projects/TKS/boards/13?modal=detail&selectedIssue=TKS-1041&assignee=6295de5db407cc0069ff3164

re: fix img-icon-misalinged

---

src/wallet/Web3WalletProvider.ts

This PR is related to TKS-1042 https://smarttokenlabs.atlassian.net/jira/software/c/projects/TKS/boards/13?modal=detail&selectedIssue=TKS-1042&assignee=6295de5db407cc0069ff3164

re: fix tkn stuck when user reject to connect a wallet

---

src/client/index.ts
src/outlet/index.ts

hi guys @snowwhitedev, @oleggrib, @BankiLouis 
This PR addresses the sonar cloud major issues raised. There were 9 found, 8 have been fixed (most managing the error handling for promises). One resolved as won't fix - where it was strangely asking for async logic to be placed around a sync function (https://sonarcloud.io/project/issues?resolutions=FALSE-POSITIVE&sinceLeakPeriod=true&types=BUG&pullRequest=662&id=TokenScript_token-negotiator)
Smoke test run against the examples from these changes made.

addressed sonar scan m issues raised.

---

package.json

Updated the package.json version for in prep for 2.6.0 release / and testing effort to ensure we're testing the new release version code.

updated the package json version in prep for release

---

sonar-project.properties
src/wallet/Web3WalletProvider.ts
src/wallet/__test__/wallet.spec.ts

This PR is for the ticket https://smarttokenlabs.atlassian.net/browse/TKS-1068

re: fix evm event hooks

---

src/outlet/index.ts

Review of change to return promise from user action, when accepting or declining to connect with a token issuer website to read attestations.

added return to resolving promise from a user action

---

README.md
index.html

Small text update made to the opening view of TKN.

updated the text to the start screen of tkn

---

CHANGELOG.md
package.json

Updates in prep for 2.7.0 release.

release prep changes

---

CHANGELOG.md
README.md
package-lock.json
package.json
src/outlet/index.ts
src/outlet/ticketStorage.ts
src/version.ts

Will merge Oleh's changes. 
Reviewed, tested and some additions made for the release prep / TODO added for a later time.

fix: 🐛 limited event "tokensupdated" when token really updated

---

src/client/auth/ticketZKProof.ts
src/outlet/auth-handler.ts
src/outlet/ticketStorage.ts

This update comments out a few work in progress changes for the EAS Auth. Allow us to merge the most up to date changes into the Staging ENV.
In the changes, some of the methods do not exist at this time which blocks staging from its build succeeding.

todo comments added to eas authchanges

---

src/outlet/whitelist.ts
src/utils/index.ts

Fixes added to allow the user to decline the connection to the off chain issuer.
- Prevents the dialog from showing the X num of times there are sub issuers per origin

fix for whitelist selection

---

src/outlet/ticketStorage.ts

Enriched attestation meta with collection id.

enrich attestation meta with collection id

---

src/client/views/select-issuers.ts
src/outlet/__tests__/outlet.spec.ts
src/outlet/ticketStorage.ts

ref branch to use a "non type" reference key for the ticketId.

added ticketId to attestation schema

---

package-lock.json
src/outlet/ticketStorage.ts
src/utils/index.ts

fixed the asn issuer

---

src/client/views/select-issuers.ts

Remove asterisk to select by exact match.

Fix: issuer query selectors

---

CHANGELOG.md

Merging change log details in prep for next patch release.

updated change log with 3.0.2 fixes

---

package.json
src/utils/support/getBrowserData.ts

defaul to re-direct mode
