.eslintignore
.eslintrc
package-lock.json
package.json
src/client/index.ts
src/core/index.ts

This PR addresses items 1-4 of the AC in #163. Resolving all linting errors is not a trivial task and should be addressed separately. I feel there is value in merging this PR now so that we can establish a baseline for progression.
ESLint has been added to package.json and can be run with  `npm run lint`. Note that warnings are currently disabled.
The original TSlint rules (tslint.json) were converted to ESLint automatically using [tslint-to-eslint-config](https://www.npmjs.com/package/tslint-to-eslint-config). tslint.json has been left in the repo for now for comparison purposes but can eventually be removed.
In an attempt to get the baseline reporting as close to TSLint as possible these additional rules were disabled:
```
"@typescript-eslint/naming-convention": "off", …
```

163 review linting implementation and resolve errors

---

jest.config.js
package-lock.json
src/client/__tests__/client.spec.ts
src/onChainTokenModule/__tests__/onchaintoken.spec.ts
src/onChainTokenModule/index.ts
src/outlet/__tests__/outlet.spec.ts
test/jest/__mocks__/mock.js
test/jest/jest.setup.js
test/jest/jest.transform.js

**Test updates and additions**
- Re-enabled the Client tests. The tests themselves did not require any code changes, but several jest configuration customisations were required due to the Torus dependencies. The last test for `addTokenThroughIframe` has been left commented out since that function does not exist.
- Added several new client tests.
- Added tests for OnChainTokenModule. Includes mocking of contract API fetch requests.
- Attempted to add a test for Outlet but hit an issue with a TypeError in `@tokenscript/attestation`. Left in as a placeholder test with a TODO comment.
**Bugs**
As a result of writing the tests for OnChainTokenModule two bugs were found in the `getOnChainAPISupportBool`. They have been fixed by this PR. Note that this function always returned true for any chain …

156 token negotiator unit tests uplift

---

src/client/messaging.ts
src/outlet/index.ts

@nicktaras small patch to fix Safari support. 
Since this is always a restriction in safari I decided to check for Safari directly rather than use the local storage check. 
Other browsers still use the iframe cookie check in case they're using stricter privacy controls.

Fix tab messaging for safari browser.

---

src/core/messaging.ts

The third party cookie check requires that the ticket is created in 
the outlet. This creates a special localStorage flag that can be checked 
via negotiator to infer cross-origin local storage access. 
The problem with this is that if the check fails, a popup is used automatically. 
This may happen when the ticket is not issued or on the ticket issuer page itself. 
Alphawallet android and many other dapp browsers do not support popups and instead 
navigate to the page in the same window. This causes a white screen with no way to return. 
This commit disables the check and only forces the use of tabs in browsers known to restrict 
iframe access to local storage, like safari:
https://stackoverflow.com/questions/63922558/safari-localstorage-not-shared-between-iframes-hosted-on-same-domain

Fix alphawallet browser android tab behaviour TKN-252

---

package-lock.json
package.json
src/client/auth/attestedAddress.ts
src/client/auth/util/SafeConnect.ts
src/wallet/SafeConnectProvider.ts

@nicktaras This PR adds support for using safe-connect attestations when the user has used a direct wallet connection. This will later be used to add NFT attestation authentication to the shopify app, and move away from UN signature auth.

feature: add support for safe-connect attestations via direct wallet connection

---

package.json

Remove `dist/` from repo, this will generate by `npm run build` job.
And I replace `prepublishOnly` task with `prepare`, which will automatically run after `npm ci/install`, and run before `npm pack/publish`. See: https://docs.npmjs.com/cli/v8/using-npm/scripts#prepare-and-prepublish
So both `npm publish` and `npm install "git://github.com/tokenScript/token-negotiator.git#staging"` should work.
And I set `"files": ["dist/"]` in `package.json`, which will limit npm package only contains `dist/` directory and `package.json`.
After all, this should fix CI https://github.com/TokenScript/token-negotiator-examples/pull/96

chore: 🤖 remove dist/ from repo

---

src/client/index.ts
src/core/index.ts
src/outlet/index.ts

@oleggrib as outlined in issue #381, this PR adds the ability for signed tokens to be returned by clients, depending on whitelist config in the outlet.

feature: add the ability for signedTokens to be returned to client

---

src/wallet/Web3WalletProvider.ts

This allows switching chain and sending a transaction on another chain. Without it, only the initial chain is allowed to send transactions.

fix: add "any" parameter to ethers instances

---

src/utils/index.ts

This PR addresses issues with error handling to correct cases where the error provided is an Error type or other object. 
This resulted in [object Object] being shown in the UI and the original error message being lost. 
A new error type has been created to wrap the original error and provide a human readable message in all cases. 
This new type could also be used to categorize errors with an error code to provide more user friendly messages.

Fix: error type handling

---

package.json
src/wallet/TorusProvider.ts
src/wallet/WalletConnectProvider.ts

This should remove the need for the vast majority of polyfills by explicitly using the UMD version of of WalletConnect & Torus. 
It's been tested on most examples after removing polyfills and is working successfully.

fix: use UMD modules for Torus & WalletConnect to fix polyfill issues

---

src/wallet/Web3WalletProvider.ts

@nicktaras I forgot to add the "any" chain parameter to WC and Torus ethers instances

fix: specify "any" network for WC & Torus ethers instance

---

src/client/index.ts

This fixes an issue caused by checking issuerConfig.tokenOrigin for on-chain tokens. It simple adds the filter parameter to include only off-chain tokens.

fix: outlet origin check for onchain tokens

---

src/wallet/WalletConnectV2Provider.ts
src/wallet/Web3WalletProvider.ts

- TextEncoder not required when explicitly importing umd module.
- Add 'any' network parameter to ethers WC v2 instance.
- Add Goerli & mumbai chain RPCs.

Fix: wallet connect v2 remove text encoder

---

src/client/index.ts
src/client/ui.ts
src/client/views/select-issuers.ts
src/client/views/token-list.ts
src/outlet/index.ts
src/utils/support/getBrowserData.ts

- Fix issues with multiple instances of token negotiator. Never use "document." within UI class, always use "viewContainer."
- Add missing error handling for off-chain token loading in redirect mode.

Fix: Token redirect load error handler

---

src/client/auth/ticketZKProof.ts
src/client/index.ts
src/client/messaging.ts
src/client/views/select-issuers.ts
src/core/messaging.ts
src/outlet/index.ts
src/utils/support/getBrowserData.ts
src/wallet/SafeConnectProvider.ts

Fixed:
- TKS-628 Redirect mode causes exception before page reload
- TKS-736 Fix tokens automatic load not triggering due to stale tokenStore
- TKS-737 Firefox permission dialog not clickable (Windows & Android). Firefox should use redirect mode
- Fix addTokenViaMagicLink returning void in redirect mode & improve outlet error handling (relates to TKS-628)

Fix: various 2.3 issues

---

package-lock.json
package.json

I updated @walletconnect/universal-provider version from 2.1.5 to ^2.45(latest is 2.4.6). 
This is the solution for TKS-608 https://smarttokenlabs.atlassian.net/jira/software/c/projects/TKS/boards/13?modal=detail&selectedIssue=TKS-686&assignee=6295de5db407cc0069ff3164

re: update wc v2 version(fix disconnect event hook)

---

src/client/index.ts
src/client/interface.ts
src/wallet/WalletConnectProvider.ts
src/wallet/WalletConnectV2Provider.ts
src/wallet/Web3WalletProvider.ts
src/wallet/__test__/wallet.spec.ts

Expose WalletConnect v2 options required for specifying chains included in the connection request.
This is require for WCv2 to be compatible with our e-commerce example for minting.

feat: Add wallet provider options for WC v2

---

package.json
src/client/index.ts
src/client/ui.ts

- Ensure this.config.issuers is kept up to date with issuers specified via the negotiate function.
- Ensure view name is set correctly and view-changed event is only emitted after successful render.
- Add viewOptions.componentIsFactory. It's impossible to determine whether a variable is a 
class constructor or a function reliably. And calling factory with new keyword breaks es6 builds.

Fix: various issues

---

package.json
src/version.ts
src/wallet/WalletConnectV2Provider.ts

Now that TN targets ES6, specifying full module path (@walletconnect/universal-provider/dist/index.es) is unnecessary and causes an error in some projects.

Patch version 2.4.2

---

.eslintrc
.prettierrc.js
package-lock.json
package.json

Hey @nicktaras this should fix most of the formatting conflicts between eslint & prettier.
And increases printWidth to be in line with CSS setting. This makes the HTML template literals a clearer to read but can be changed back if you want.

Fix: prettier eslint format conflict

---

README.md

Minor change added to remove the notice of support for Cronos and Avalanche Test Net (Expires 15th May 2023)

removed unsupported chains

---

package-lock.json
src/wallet/Web3WalletProvider.ts

This PR is related to ticket https://smarttokenlabs.atlassian.net/browse/TKS-1047
I removed deprecated solana event hooks and some other few lines

re: remove deprecated solana event hooks and lines from web3walletprovider

---

src/outlet/index.ts
src/outlet/localOutlet.ts
src/outlet/ticketStorage.ts

Rather than restricting signedToken to domains that are whitelisted by the issuer, this allows domains whitelisted by the user to gain access to the signedToken too. 
- signedTokenWhitelist remains but just grants access for the domain to get the token without user permission prompt
- token is returned to all domains with permission either given by the issuer or by the user

Feat: always include signed token

---

.github/workflows/tn-p1.yml
.github/workflows/tn.yml

Hi @nicktaras . This PR will use `gh-pages` branch for deploy: https://github.com/TokenScript/token-negotiator/tree/gh-pages
This will support multiple version.
https://tokenscript.github.io/token-negotiator/negotiator.js will always point the latest version, and the supported versions  can be found under https://tokenscript.github.io/token-negotiator/.
When push a tag, it will deploy a tag version directory. E.g `v2.6.0`, the directory name is the same as tag name.

ci: 🎡 use gh-pages branch for deploy

---

.github/workflows/tn-p1.yml
.github/workflows/tn-snapshot.yml

Temporarily disable to make dev pipeline easier to manage. To work better this needs workflow dispatch inputs in tn-snapshot at least, so a snapshot build could force using a particular version of att. lib.

Chore: disable attest lib snapshot

---

src/client/auth/signedUNChallenge.ts
src/client/auth/util/UN.ts

As part of the `common-api` work, we migrated the UN creation API from `winding-tree`, and we made a change regarding the HTTP method from Get to Post, it's mainly because this endpoint is more like creating a new UN than reading an existing UN, but open to discuss.
__Note:__ We were planning to terminate the winding-tree backend later when this migration is released, especially considering the UN endpoint is only internally used by us, but please feel free to raise your concern if there is other unexpected impact (as the previous TN package will still have the default UN endpoint pointing to winding tree), cheers cc @foxgem

Switch default UN creation api to common-api

---

src/client/index.ts
src/client/interface.ts

This allows type hinting for developers registering events with token negotiator. 
The eventSender function is also modified with generics as an alternative to overload signatures.

feat: Add generic argument types to "on" and "eventSender" functions

---

src/client/__tests__/client.spec.ts
src/client/index.ts

Adjusted the logic to utilise the attestations collection id. Removed the need for the end developer to send this separately to the unsigned token.
The code changes have been made and smoke tested across the examples for single and multi.

remove the requirement to send issuer id via authenticate method

---

package-lock.json
package.json
src/client/auth/ticketZKProof.ts
src/client/auth/ticketZKProofMulti.ts
src/client/index.ts
src/client/interface.ts
src/core/constants.ts
src/core/eas.ts
src/outlet/getUseToken.ts
src/outlet/index.ts
src/outlet/interfaces.ts
src/outlet/localOutlet.ts
src/outlet/ticketStorage.ts
src/wallet/WalletConnectV2Provider.ts
src/wallet/Web3WalletProvider.ts

- Add option to specify custom RPC map for use in EAS revocation checking & walletconnect connections.
  Each key (chain) in the config overrides the default inbuilt URLs.
- Add option to skip revocation check when importing the attestation into the outlet.

Feat: rpc and revoke check options

---

src/client/index.ts
src/client/interface.ts
src/client/tokenStore.ts
src/client/views/token-list.ts
src/outlet/localOutlet.ts
src/outlet/ticketStorage.ts

- Add ticketStorage method to delete token from collection by providing tokenId or DecodedToken object.
- Change ticket storage to a public readonly property of LocalOutlet.
- Define the interface for EventSenderTokensSelected.
- Remove redundant EventSenderTokens interface.

feat: Add ticket delete method and various other improvements
